name: Release to GitHub Container Registry

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/go/bin
            ~/bin/protoc
            ~/.cache
          key: ${{ runner.os }}-sip-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-sip

      - name: Docker metadata
        id: docker-md
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Download Go modules
        run: go mod download

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./build/sip/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.docker-md.outputs.tags }}
          labels: ${{ steps.docker-md.outputs.labels }}